<#
  build-app.ps1 — assemble the InWallz app payload for the Windows installer.

  Produces  dist\InWallzApp\app\  containing:
    build\      the React UI (built same-origin, API at /api)
    backend\    the Node backend + production node_modules (pure JS, no native)

  The backend is run by the bundled portable Node (see PACKAGING.md); there is
  no pkg/native compilation, so this payload is portable across machines.

  Usage (from the repo root):
    powershell -ExecutionPolicy Bypass -File packaging\build-app.ps1
#>

param(
    [string]$Root = (Resolve-Path "$PSScriptRoot\.."),
    [string]$Out  = (Join-Path (Resolve-Path "$PSScriptRoot\..") "dist\InWallzApp")
)

$ErrorActionPreference = "Stop"
Write-Host "== InWallz app payload build ==" -ForegroundColor Cyan
Write-Host "repo: $Root"
Write-Host "out : $Out"

# 1) Build the React UI, same-origin (/api) so one machine serves UI + API.
Write-Host "`n[1/4] Building React UI (REACT_APP_API_URL=/api)..." -ForegroundColor Yellow
Push-Location $Root
if (Test-Path "node_modules\.cache") { Remove-Item "node_modules\.cache" -Recurse -Force }
$env:REACT_APP_API_URL = "/api"
$env:CI = "true"
npx react-scripts build
Remove-Item Env:\REACT_APP_API_URL, Env:\CI
Pop-Location
if (-not (Test-Path "$Root\build\index.html")) { throw "React build failed" }

# 2) Fresh staging tree.
Write-Host "`n[2/4] Staging payload..." -ForegroundColor Yellow
if (Test-Path $Out) { Remove-Item $Out -Recurse -Force }
$appDir = Join-Path $Out "app"
New-Item -ItemType Directory -Force -Path $appDir | Out-Null

# build\
Copy-Item "$Root\build" (Join-Path $appDir "build") -Recurse

# backend\ (exclude node_modules, .env, and local dev cruft)
$backendOut = Join-Path $appDir "backend"
robocopy "$Root\backend" $backendOut /E /XD node_modules /XF .env *.log | Out-Null

# 3) Production backend dependencies (pure JS now that bcrypt -> bcryptjs).
Write-Host "`n[3/4] Installing production backend deps..." -ForegroundColor Yellow
Push-Location $backendOut
npm ci --omit=dev --no-audit --no-fund 2>$null
if ($LASTEXITCODE -ne 0) { npm install --omit=dev --no-audit --no-fund }
Pop-Location

# 4) .env template (the installer fills the generated values).
Write-Host "`n[4/4] Writing .env template..." -ForegroundColor Yellow
@"
# Generated by the InWallz installer per machine.
PORT=5000
DB_HOST=127.0.0.1
DB_USER=inwallz
DB_PASSWORD=__DB_PASSWORD__
DB_NAME=inwallz_billing
DB_PORT=3306
JWT_SECRET=__JWT_SECRET__
JWT_EXPIRES_IN=8h

# Local-first sync (the installer sets these):
SYNC_ROLE=local
CLOUD_SYNC_URL=https://billing.inwallz.in
ACTIVATION_KEY=__ACTIVATION_KEY__
SYNC_INTERVAL_MS=15000
"@ | Out-File (Join-Path $backendOut ".env.template") -Encoding utf8

$size = "{0:N1} MB" -f ((Get-ChildItem $Out -Recurse | Measure-Object Length -Sum).Sum / 1MB)
Write-Host "`nPayload ready at $Out ($size)" -ForegroundColor Green
Write-Host "Next: bundle portable Node + MySQL + NSSM, then compile installer.iss (see PACKAGING.md)."
